# Generated by Django 3.0.5 on 2020-08-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
