# Generated by Django 3.0.5 on 2020-08-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20200810_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
