# Generated by Django 3.0.5 on 2020-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20200810_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
