# Generated by Django 3.0.5 on 2020-08-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20200811_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
